title: Lukas Strelecky
url: "lstrelecky.github.io"

remote_theme: ankitsultana/researcher@gem
plugins:
  - jekyll-feed

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Contact"
   link: "contact"
