title: Lukas Strelecky
url: "lstrelecky.github.io"
baseurl: "/docs"

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

remote_theme: ankitsultana/researcher@gem
plugins:
  - jekyll-feed

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/docs/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
